<?php echo $this->tag->linkTo(["/user", "Log Out", 'class' => 'btn btn-success']); ?>
<div class="dropdown float-right">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <?php echo $locale->_('lang') ?>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "&locale=en" ?>">English</a>
        <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "&locale=fr" ?>">French</a>
        <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "&locale=hi" ?>">Hindi</a>
        <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "&locale=ja" ?>">Japanese</a>
    </div>
</div>
<h1>Add role</h1>

<?php echo $this->tag->form("/access/addrole?role=admin"); ?>

<p>
    <label for="roles">Add role</label>
    <?php echo $this->tag->textField("roles");
    echo $this->tag->submitButton(["Add", "class" => "btn btn-primary"]);
    echo $errorMsg;
    ?>
</p>
</form>

<h3>Current Roles - </h3>
<?php
if ($roles)
    if ($roles->count() > 0) {
        foreach ($roles as $role) { ?>
        <p>
            <?php
            echo $role->role;
            ?>
        </p> <?php  };
        } ?>