<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>Users</title>
</head>

<body>
    <?php
    include '../app/views/uicomponents/nav.phtml';
    include '../app/views/uicomponents/language.phtml';
    ?>


    <?php
    if ($users)
        if ($users->count() > 0) {
    ?>
        <table class="table table-bordered table-hover">
            <thead class="thead-light">
                <tr>
                    <th> <?php echo $locale->_('user') . $locale->_('id'); ?></th>
                    <th><?php echo $locale->_('name'); ?></th>
                    <th><?php echo $locale->_('email'); ?></th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <?php


                foreach ($users as $user) { ?>
                    <tr>
                        <td><?php echo $user->user_id; ?></td>
                        <td><?php echo $user->name; ?></td>
                        <td><?php echo $user->email; ?></td>
                        <td><a href="/user/delete?id=<?php echo $user->user_id; ?>">delete</a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>

    <?php
        }; ?>
</body>

</html>